apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
  template: 
    metadata:
      labels:
        component: backend
    spec: 
      containers:
        - name: backend
          image: dingyi2000/backend
          ports:
            - containerPort: 8092
          env:
            - name: DB_URL
              value: jdbc:postgresql://db-service:5432/local?currentSchema=joinews