apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: web
          image: dingyi2000/web
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_BASE_URL
              value: http://3.19.246.208:32571
